package protocol;

/** All JSON protocol message types exchanged by the TCP chat system. */
public enum MessageType {
    LOGIN, CREATE_ROOM, ROOM_LIST, JOIN_ROOM, LEAVE_ROOM, CHAT, WHISPER, USER_LIST, LOGOUT,
    LOGIN_SUCCESS, LOGIN_FAIL, SERVER_FULL, SERVER_BUSY, CONNECTION_LIMIT_EXCEEDED,
    LOGIN_TIMEOUT, IDLE_TIMEOUT, RATE_LIMIT_EXCEEDED, AUTH_FAIL,
    CREATE_ROOM_SUCCESS, CREATE_ROOM_FAIL, ROOM_LIST_RESULT,
    JOIN_ROOM_SUCCESS, JOIN_ROOM_FAIL, LEAVE_ROOM_SUCCESS, LEAVE_ROOM_FAIL,
    CHAT_BROADCAST, WHISPER_SENT, WHISPER_RECEIVED, WHISPER_FAIL,
    USER_LIST_RESULT, SYSTEM_MESSAGE, SERVER_SHUTDOWN, ERROR
}
